[scoop.buckets]
extras = "https://github.com/ScoopInstaller/Extras"
games = "https://github.com/Calinou/scoop-games"
main = "https://github.com/ScoopInstaller/Main"
nerd-fonts = "https://github.com/matthewjberger/scoop-nerd-fonts"
versions = "https://github.com/ScoopInstaller/Versions"
rodrigost23_scoop-bucket= "https://github.com/rodrigost23/scoop-bucket"
hoilc_scoop-lemon= "https://github.com/hoilc/scoop-lemon"
nonportable=""

[scoop]
bootstrap = ["7zip", "git", "aria2", "gsudo", "wixtoolset", "innounp"]
base = [
    "chezmoi",
    "everything",
    "zoxide",
    "rga",
    "starship",
    "nu",
    "pwsh",
    "mingw",
    "wezterm",
    "fd",
    "fzf",
    "lazygit",
    "delta",
    "bat",
    "sfsu",
    "scoop-search",
    # "mpv",
    "nonportable/icaros-np",
    # "yt-dlp",
    "waterfox",
    "floorp",
    "hoilc_scoop-lemon/betterbird",
    "notepadplusplus",
    "vscode",
    "carapace-bin"
]
work = [
    "games/epic-games-launcher",
    # "extras/ripcord",
    "extras/slack",
    "main/glab",
    "rodrigost23_scoop-bucket/alienfx-tools"
]
gaming = [
    "games/steam"
]
home = [
    "extras/archisteamfarm"
]
    # # Ps modules
    # "scoop-completion",
    # "dockercompletion",
    # "z",
    # "zlocation",
    # "psfzf",
    # "winget-ps",
    # "powertab",
    # "posh-git",
    # "lazy-posh-git",
    # "pscolor",
    # "powershell-beautifier",
    # "terminal-icons",

    # # CLI
    # "clink",
    # "clink-completions",
    # "clink-flex-prompt"

[winget]
work = [
    "TeamDriveSystems.TeamDrive",
]
gaming = [
    "MyGames.GameCenter --ignore-security-hash",
]
home = []

