[flags]
# makes process list cpu% add up to one (obfuscates unused cpu)
current_usage = false 

enable_gpu = true
group_processes = true
mem_as_value = true
tree = false
show_table_scroll_position = true

temperature_type = "celsius"
basic = false
hide_avg_cpu = false
dot_marker = false
unnormalized_cpu = false

[processes]
# Pick which columns you want to use in any order.
columns = ["cpu%", "mem%", "pid", "name", "read", "write", "tread", "twrite", "state", "user", "time", "gmem%", "gpu%"]

[mount_filter]
is_list_ignored = true
list = ["/.swap*"]
regex = true
case_sensitive = false
whole_word = true

[disk_filter]
is_list_ignored = true
list = ["/dev/loop\\d+"]
regex = true

[[row]]
  [[row.child]]
  ratio=2
  type="cpu"
  [[row.child]]
  type="mem"
[[row]]
  [[row.child]]
  type="net"
  ratio=2
  [[row.child]]
  type="disk"
  ratio=2
  [[row.child]]
  type="temp"
[[row]]
  ratio=3
  [[row.child]]
  type="proc"
  default=true