[scoop.repositories]
extras = "https://github.com/ScoopInstaller/Extras"
games = "https://github.com/Calinou/scoop-games"
main = "https://github.com/ScoopInstaller/Main"
nerd-fonts = "https://github.com/matthewjberger/scoop-nerd-fonts"
versions = "https://github.com/ScoopInstaller/Versions"

[scoop]
packages = [
    "aria2",
    "7zip",
    "archisteamfarm",

    # Ps modules
    "scoop-completion",
    "dockercompletion",
    "z",
    "zlocation",
    "psfzf",
    "winget-ps",
    "powertab",
    "posh-git",
    "lazy-posh-git",
    "pscolor",
    "powershell-beautifier",
    "terminal-icons",

]

[winget]
packages = [
    "GNU.Wget2",
    # The DSC resource cannot (?) install the below
    "MyGames.GameCenter --ignore-security-hash",
]

    # - chezmoi
    # - cutter
    # - dnspyex
    # - docker
    # - erdtree
    # - everything
    # - fd
    # - FiraCode-NF
    # - FiraCode
    # - FiraCode-NF-Mono
    # - ghidra
    # - fzf
    # - git
    # - gitleaks
    # - gitui
    # - graphviz
    # - grep
    # - Hack-NF-Mono
    # - Hack-NF
    # - hcloud
    # - IntelOneMono-NF
    # - kind
    # - lazygit
    # - scoop-search
    # - starship
    # - sudo
    # - tokei
    # - vcpkg
    # - yt-dlp
    # - x64dbg
    # - zoxide
    # - go
    # - powertoys
    # - pulumi
    # - pwsh
    # - opentofu
    # - ripgrep
    # - nerdctl
    # - helm
    # - gzip
    # - mingw
    # - make
    # - unzip
    # - minikube
    # - kubectl
    # - autohotkey
    # - vcpkg